// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: merchant.proto

package merchant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMerchantRequest) Reset() {
	*x = RegisterMerchantRequest{}
	mi := &file_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMerchantRequest) ProtoMessage() {}

func (x *RegisterMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMerchantRequest.ProtoReflect.Descriptor instead.
func (*RegisterMerchantRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterMerchantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterMerchantRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMerchantResponse) Reset() {
	*x = RegisterMerchantResponse{}
	mi := &file_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMerchantResponse) ProtoMessage() {}

func (x *RegisterMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMerchantResponse.ProtoReflect.Descriptor instead.
func (*RegisterMerchantResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterMerchantResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type GetMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantRequest) Reset() {
	*x = GetMerchantRequest{}
	mi := &file_merchant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantRequest) ProtoMessage() {}

func (x *GetMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{2}
}

func (x *GetMerchantRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type GetMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	KycVerified   bool                   `protobuf:"varint,4,opt,name=kyc_verified,json=kycVerified,proto3" json:"kyc_verified,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantResponse) Reset() {
	*x = GetMerchantResponse{}
	mi := &file_merchant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantResponse) ProtoMessage() {}

func (x *GetMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{3}
}

func (x *GetMerchantResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetMerchantResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMerchantResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetMerchantResponse) GetKycVerified() bool {
	if x != nil {
		return x.KycVerified
	}
	return false
}

func (x *GetMerchantResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetMerchantResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_merchant_proto protoreflect.FileDescriptor

const file_merchant_proto_rawDesc = "" +
	"\n" +
	"\x0emerchant.proto\x12\bmerchant\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x17RegisterMerchantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\";\n" +
	"\x18RegisterMerchantResponse\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"5\n" +
	"\x12GetMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"\xf9\x01\n" +
	"\x13GetMerchantResponse\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fkyc_verified\x18\x04 \x01(\bR\vkycVerified\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xb8\x01\n" +
	"\x0fMerchantService\x12Y\n" +
	"\x10RegisterMerchant\x12!.merchant.RegisterMerchantRequest\x1a\".merchant.RegisterMerchantResponse\x12J\n" +
	"\vGetMerchant\x12\x1c.merchant.GetMerchantRequest\x1a\x1d.merchant.GetMerchantResponseB*Z(services/merchant-service/proto;merchantb\x06proto3"

var (
	file_merchant_proto_rawDescOnce sync.Once
	file_merchant_proto_rawDescData []byte
)

func file_merchant_proto_rawDescGZIP() []byte {
	file_merchant_proto_rawDescOnce.Do(func() {
		file_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_proto_rawDesc), len(file_merchant_proto_rawDesc)))
	})
	return file_merchant_proto_rawDescData
}

var file_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_merchant_proto_goTypes = []any{
	(*RegisterMerchantRequest)(nil),  // 0: merchant.RegisterMerchantRequest
	(*RegisterMerchantResponse)(nil), // 1: merchant.RegisterMerchantResponse
	(*GetMerchantRequest)(nil),       // 2: merchant.GetMerchantRequest
	(*GetMerchantResponse)(nil),      // 3: merchant.GetMerchantResponse
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
}
var file_merchant_proto_depIdxs = []int32{
	4, // 0: merchant.GetMerchantResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: merchant.GetMerchantResponse.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: merchant.MerchantService.RegisterMerchant:input_type -> merchant.RegisterMerchantRequest
	2, // 3: merchant.MerchantService.GetMerchant:input_type -> merchant.GetMerchantRequest
	1, // 4: merchant.MerchantService.RegisterMerchant:output_type -> merchant.RegisterMerchantResponse
	3, // 5: merchant.MerchantService.GetMerchant:output_type -> merchant.GetMerchantResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_merchant_proto_init() }
func file_merchant_proto_init() {
	if File_merchant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_proto_rawDesc), len(file_merchant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_proto_goTypes,
		DependencyIndexes: file_merchant_proto_depIdxs,
		MessageInfos:      file_merchant_proto_msgTypes,
	}.Build()
	File_merchant_proto = out.File
	file_merchant_proto_goTypes = nil
	file_merchant_proto_depIdxs = nil
}
